[window]
padding = { x = 5, y = 5 }
dimensions = { columns = 110, lines = 30 }
opacity=0.9

[font]
normal = { family = "JetBrains Mono" }
size = 13

[selection]
save_to_clipboard = true

[mouse]
bindings = [{ mouse = "Right", action = "Paste" }]

[cursor]
style= { shape = "Block", blinking =  "On" }
