set -g mouse on

set -g default-command 'exec "$(command -v zsh || echo "${SHELL:-/bin/sh}")" -l'

# indexing from 1 for convenience
set -g base-index 1
setw -g pane-base-index 1

bind r "source-file $HOME/.config/tmux/tmux.conf \; display-message 'Config reloaded!'"

# plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-powerkit' #macos requires up-to-date bash from brew

set -g @powerkit_plugins "hostname,cpu,memory,datetime,battery"
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "storm"
set -g @powerkit_transparent "true"
set -g @powerkit_plugin_datetime_format '%d.%m.%Y %H:%M'

run-shell 'tmux set -g @tpack-config "$HOME/.config/tmux/tmux.conf"'
run 'tpack init'
